my:
 name: github
 email: github@github.com
book:
  greeting: Welcome from config-service properties! 
---
spring:
  config:
    activate:
      on-profile: prod
my.name: prod
my.email: prod@prod.com
